version: "3.8"
services:
  
  rabbitmq:
    image: rabbitmq
    networks:
      - events
  
  database:
    image: postgres:11.5
    networks:
      - data

  vegetables:
    image: service-mesh-presentation/vegetables
    build:
      context: ../apps
      dockerfile: Dockerfile
    command: all # Stub to be removed with final service definition
    networks:
      - vegetables
    ports:
      - 8080:8080

  superheroes:
    image: service-mesh-presentation/superheroes
    build:
      context: ../apps
      dockerfile: Dockerfile
    command: all # Stub to be removed with final service definition
    networks:
      - superheroes
    ports:
      - 8081:8080
      

networks:
  vegetables:
  superheroes:
  data:
  events:

